### ISSUE TITLE
Add Adapt logo to the src directory

### ISSUE THREAD

**Issue by jesseday** [adaptdk/adapt-toolkit-color-picker#10]
In order to submit to the contentful app marketplace, we must include a logo.

1. Add the adapt logo as an svg to the src directory of this repo.  EG `src/logo.svg`

**Comment by Toxicom** [comment]
Trying to find where can I get a high quality adapt logo (both svg and png), will upload once i get that

**Comment by Toxicom** [comment]
Added logo to files (both svg and png) and also added it to config screen
![image](https://github.com/adaptdk/adapt-toolkit-color-picker/assets/69549795/fcd6f9c9-34c5-405d-9ed7-91f5ecda19d0)
