### ISSUE TITLE
App needs a name and description of features

### ISSUE THREAD

**Issue by jesseday** [adaptdk/adapt-toolkit-color-picker#11]
In order to submit to the Contentful Marketplace, the app requires that we define the following:

1.  clear name for your app - generally your business/product name
2. A tagline, description, feature list, and requirements list for your app

# Notes
My suggestions:

**Name:** Adapt Toolkit: Color Tokens 
**Description:** Configure your design system color tokens in Contentful in order to keep your editors, developers, and designers all on the same page.

**Comment by Toxicom** [comment]
Where should this be added? I've changed the app name in code: https://github.com/adaptdk/adapt-toolkit-color-picker/commit/c086f62b7df251570cccbde2e4947f2324fa8d88

**Comment by jesseday** [comment]
I think this is probably okay.  we'll submit the app and see what happens
