### ISSUE TITLE
Document installation, configuration, and usage

### ISSUE THREAD

**Issue by jesseday** [adaptdk/adapt-toolkit-color-picker#8]
# Summary

In order to get the app in the Contentful Marketplace the app, it must be documented.  Please document the following

1. Once installed, how do I configure the app?  Eg, do I have to add some global colors?
2. How do I configure the app on a particular field?
3. How do I validate against colors provided in the app?
4. What type of output can I expect from the api when I go to use the app?  How might this fit into my design system?

**Comment by Toxicom** [comment]
Should I add this to the readme? Somewhere in the app? Just external google doc that we add to marketplace's readme?
