### ISSUE TITLE
Update readme for submission to the Contentful Marketplace

### ISSUE THREAD

**Issue by jesseday** [adaptdk/adapt-toolkit-color-picker#9]
In order to submit our app to the Contentful Marketplace, we have to add links to the following in our readme:

1. link to our privacy policy: https://adaptagency.com/privacy-policy
2. Link to this repositories issue queue for opening issues or feature requests: https://github.com/adaptdk/contentful-color-app/issues

**Comment by Toxicom** [comment]
140ed3842e175c031e9226ce545983f1200f4162

**Comment by jesseday** [comment]
perfect, thank you
